?function_name: function_definition "(" parameter+ ")" "{" body "}"

?function_definition : CNAME

?body: "return" operation ";"

?parameter: name_var ("," name_var)+

?operation: sum_expr

?sum_expr: prod_expr
        | sum_expr "+" prod_expr

?prod_expr: atom_expr
        | prod_expr "*" atom_expr

?atom_expr: CNAME

?operand: 
        |"+"
        |"*"
 
?name_var: CNAME

%import common.CNAME
%import common.WS_INLINE
%import common.WS
%import common.NUMBER

%ignore WS_INLINE
%ignore WS